# Generated by Django 5.0.3 on 2024-03-19 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2024, 3, 19, 0, 13, 55, 604860, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
